version: 0.2
env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /sample-python-server/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /sample-python-server/docker-credentials/password

phases:
  install:
    runtime-versions:
      python: 3.13
  pre_build:
      commands:
        - echo "Installing dependencies..."
        - pip install -r requirements.txt
  build:
      commands:
        - echo "Building Docker image..."
        - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
        - docker build -t "docker.io/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest" .
        - docker push "docker.io/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest"
  post_build:
      commands:
        - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
  base-directory: ../simple-python-app